version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
    environment:
    - ANDROID_HOME: '/opt/android/sdk'
    steps:
    - checkout
    - run:
        name: build-android
        command: 'ls /opt/'
