version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
      - image: circleci/android:api-26-alpha
    steps:
    - run:
        name: update-npm
        command: 'sudo npm install -g npm@latest'
    - run:
        name: npm-install
        command: 'npm install'
