version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
    environment:
    - JVM_OPTS: -Xmx4g
    - ANDROID_HOME: '/opt/android/sdk'
    steps:
    - run:
        name: node-install
        command: |
          curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
          sudo apt-get install -y nodejs
    - checkout
    - run:
        name: npm-install
        command: 'npm install'
    - run:
        name: build-android
        command: './resources/circle-ci/android/build-android.sh'
